apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: toxindex-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
        - name: backend
          image: us-docker.pkg.dev/toxindex/toxindex-backend/backend:latest
          command: ["gunicorn", "--worker-class", "geventwebsocket.gunicorn.workers.GeventWebSocketWorker", "-w", "2", "--timeout", "120", "--keep-alive", "5", "-b", "0.0.0.0:6513", "webserver.app:app"]
          ports:
            - containerPort: 6513
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
            - name: DISABLE_CLOUD_LOGGING
              value: "true"  # Temporarily disable Cloud Logging to prevent timeout issues
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 6513
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 6513
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
      volumes:
      volumes: 
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: toxindex-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"6513":{}}}'
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 6513
      targetPort: 6513 