apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: toxindex-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
        - name: backend
          image: us-docker.pkg.dev/toxindex/toxindex-backend/backend:latest
          ports:
            - containerPort: 6513
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
      volumes:
      volumes: 
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: toxindex-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6513 