apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-rap
  namespace: toxindex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-rap
  template:
    metadata:
      labels:
        app: celery-worker-rap
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
      - name: celery-worker-rap
        image: us-docker.pkg.dev/toxindex/toxindex-backend/probra:latest
        command: ["python", "-m", "celery", "-A", "workflows.celery_worker_probra", "worker", "--loglevel=info", "-Q", "probra"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
