apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: toxindex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: us-docker.pkg.dev/toxindex/toxindex-backend/backend:latest
        command: ["celery", "-A", "workflows.celery_worker", "worker", "--loglevel=info"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT 