apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-raptool
  namespace: toxindex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-raptool
  template:
    metadata:
      labels:
        app: celery-worker-raptool
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
      - name: celery-worker-raptool
        image: us-docker.pkg.dev/toxindex/toxindex-backend/raptool:latest
        command: ["python", "-m", "celery", "-A", "workflows.celery_worker_raptool", "worker", "--loglevel=info", "-Q", "raptool"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
