apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-pathway
  namespace: toxindex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-pathway
  template:
    metadata:
      labels:
        app: celery-worker-pathway
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
      - name: celery-worker-pathway
        image: us-docker.pkg.dev/toxindex/toxindex-backend/pathway:latest
        command: ["celery", "-A", "workflows.celery_worker", "worker", "--loglevel=info", "-Q", "pathway"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
