apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-ranking
  namespace: toxindex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-ranking
  template:
    metadata:
      labels:
        app: celery-worker-ranking
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
      - name: celery-worker-ranking
        image: us-docker.pkg.dev/toxindex/toxindex-backend/ranking:latest
        command: ["python", "-m", "celery", "-A", "workflows.celery_worker_ranking", "worker", "--loglevel=info", "-Q", "ranking", "-c", "2", "--max-tasks-per-child", "1"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
            ephemeral-storage: "10Gi"
          limits:
            memory: "8Gi"
            cpu: "2000m"
            ephemeral-storage: "10Gi"