apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-general
  namespace: toxindex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker-general
  template:
    metadata:
      labels:
        app: celery-worker-general
    spec:
      serviceAccountName: toxindex-app-sa
      containers:
      - name: celery-worker-general
        image: us-docker.pkg.dev/toxindex/toxindex-backend/general:latest
        command: ["celery", "-A", "workflows.celery_worker", "worker", "--loglevel=info", "-Q", "default,probra,openai"]
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
