version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - toxindex-data:/data
    ports:
      - 5415:5432

  # postgrest:
  #   image: postgrest/postgrest:v11.2.0
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  #     PGRST_DB_SCHEMA: public
  #     PGRST_DB_ANON_ROLE: web_anon
  #     PGRST_SERVER_PORT: 3000
  #   volumes:
  #     - ./path/to/postgrest.conf:/etc/postgrest.conf
  #   depends_on:
  #     - postgres

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres

  webserver:
    build:
      context: ./webserver
    ports:
      - "6513:6513"
    volumes:
      - ./webserver/webserver:/webserver
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_TEST_SECRET_KEY: ${STRIPE_TEST_SECRET_KEY}
      WEBSERVER_SERVER_NAME: ${WEBSERVER_SERVER_NAME}
      WEBSERVER_PREFERRED_URL_SCHEME: ${WEBSERVER_PREFERRED_URL_SCHEME}
      FLASK_APP_SECRET_KEY: ${FLASK_APP_SECRET_KEY}
    depends_on:
      - postgres
      - flyway
  
  report:
    build:
      context: ./report
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6516:6515"
    volumes:
      - ./report:/report
    depends_on:
      - postgres
      - flyway
  
  search:
    build:
      context: ./search
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6515:6515"
    volumes:
      - ./search:/search
    depends_on:
      - postgres
      - flyway
    
volumes:
  toxindex-data:
