version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - toxindex-data:/data
    ports:
      - 5415:5432

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres

  webserver:
    build:
      context: ./webserver
    ports:
      - "6513:6513"
    volumes:
      - ./webserver/webserver:/webserver
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - flyway

  upload:
    build:
      context: ./upload
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./upload:/upload
    ports:
      - "6514:5000"
  
  report:
    build:
      context: ./report
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6515:6515"
    volumes:
      - ./report:/report
    depends_on:
      - postgres
      - flyway
    
volumes:
  toxindex-data:
