# Data directory and cloud service configuration for toxindex
# This file centralizes all data path definitions and cloud service configurations

# Base data directory (relative to project root)
# Note: Most data is now in cloud services, only logs and temp files are local
data_root: "data"

# Subdirectories within data/ (local only)
directories:
  # Temporary files (short-lived, can be cleaned up)
  # Used for processing temporary files that need to be cleaned up
  tmp: "tmp"
  
  # Application logs (local for debugging and monitoring)
  # Logs are still stored locally for easy access and debugging
  logs: "logs"
  
  # Local cache files (minimal, most caching is in Redis)
  # Only for file-based caches that can't be stored in Redis
  cache: "cache"
  
  # Local temporary outputs (minimal, most outputs go to GCS)
  # Only for temporary processing outputs
  outputs: "outputs"

# Full path definitions (computed from data_root + directories)
paths:
  # Base data directory
  data: "${data_root}"
  
  # Individual subdirectories (local only)
  tmp: "${data_root}/${directories.tmp}"
  logs: "${data_root}/${directories.logs}"
  cache: "${data_root}/${directories.cache}"
  outputs: "${data_root}/${directories.outputs}"

# Cache subdirectories (local file caches only)
# Note: Most caching is now handled by Redis
cache_subdirs:
  chemprop_predictions: "function_cache/chemprop_predictions_cache"
  parse_chemicals: "function_cache/parse_chemicals"

# Session subdirectories (local files only)
# Note: Most session data is now stored in Cloud SQL
session_subdirs:
  temp_sessions: "sessions/temp"

# Cloud service configurations
# These are primarily for documentation and future configuration management
cloud_services:
  # Redis Memorystore configuration
  redis:
    service: "Redis Memorystore"
    purpose: "Caching, session storage, task queue"
    environment_variables:
      - "REDIS_HOST"
      - "REDIS_PORT"
    notes: "Primary caching and session storage"
  
  # Google Cloud Storage configuration
  gcs:
    service: "Google Cloud Storage"
    purpose: "File storage, uploads, outputs"
    environment_variables:
      - "GCS_BUCKET_NAME"
    bucket: "toxindex-uploads"
    notes: "All file uploads and outputs stored here"
  
  # Cloud SQL configuration
  cloud_sql:
    service: "Cloud SQL (PostgreSQL)"
    purpose: "Database, user data, chat sessions"
    environment_variables:
      - "PGHOST"
      - "PGPORT"
      - "PGDATABASE"
      - "PGUSER"
      - "PGPASSWORD"
    notes: "Primary database for all application data"

# Migration notes
migration_notes:
  - "File uploads: Local filesystem → GCS bucket"
  - "Chat sessions: Local files → Cloud SQL database"
  - "Caching: Local files → Redis Memorystore"
  - "Outputs: Local files → GCS bucket"
  - "Logs: Still local (for debugging and monitoring)"
  - "Temp files: Still local (for processing)" 